{{- if .Values.storage.mergeConfigFromExternalSecret }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "luna-multiplayer.fullname" . }}-config
  labels:
    {{- include "luna-multiplayer.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.storage.mergeConfigFromExternalSecret.secretStore }}
    kind: SecretStore
  target:
    name: {{ include "luna-multiplayer.fullname" . }}-config
    template:
      templateFrom:
        - configMap:
            name: {{ include "luna-multiplayer.fullname" . }}-config
            items:
              {{- range $key, $value := .Values.config }}
              - key: {{ $key }}
              {{- end}}
  data:
    {{ range .Values.storage.mergeConfigFromExternalSecret.keys }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $.Values.storage.mergeConfigFromExternalSecret.remoteKey }}
        property: {{ . }}
    {{ end }}
{{- end }}
