apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "luna-multiplayer.fullname" . }}
  labels:
    {{- include "luna-multiplayer.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "luna-multiplayer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "luna-multiplayer.selectorLabels" . | nindent 8 }}
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "luna-multiplayer.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 13 }}
          volumeMounts:
            - name: config
              mountPath: /LMPServer/Config
            - name: universe
              mountPath: /LMPServer/Universe
            - name: plugins
              mountPath: /LMPServer/Plugins
            - name: logs
              mountPath: /LMPServer/logs
          ports:
            - containerPort: {{ .Values.gameService.port }}
              protocol: UDP
            - containerPort: {{ .Values.webService.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      initContainers:
        - name: copy-config
          image: busybox:latest
          command: [ 'sh', '-c', 'cp /config/* /LMPServer/Config' ]
          volumeMounts:
            - name: external-config
              mountPath: /config/
            - name: config
              mountPath: /LMPServer/Config
      volumes:
        - name: config
          emptyDir: {}
        - name: external-config
          {{- if .Values.storage.mergeConfigFromExternalSecret }}
          secret:
            secretName: {{ include "luna-multiplayer.fullname" . }}-config
          {{- else }}
          configMap:
            name: {{ include "luna-multiplayer.fullname" . }}-config
          {{- end }}
        - name: universe
          persistentVolumeClaim:
            claimName: {{ include "luna-multiplayer.fullname" . }}-universe
        - name: plugins
          persistentVolumeClaim:
            claimName: {{ include "luna-multiplayer.fullname" . }}-plugins
        - name: logs
          emptyDir: {}
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
