version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      regular-updates:
        update-types:
          - "minor"
          - "patch"
